Insert into MBMS.DEPARTMENT (DEPT_NO,DEPT_NAME,BOSS_NO,MGR_DEPT_NO) values (10,'SI사업부','it1010',NULL);
Insert into MBMS.DEPARTMENT (DEPT_NO,DEPT_NAME,BOSS_NO,MGR_DEPT_NO) values (11,'ICT사업팀','it1011',NULL);
Insert into MBMS.DEPARTMENT (DEPT_NO,DEPT_NAME,BOSS_NO,MGR_DEPT_NO) values (12,'SI사업팀','it1012',NULL);
Insert into MBMS.DEPARTMENT (DEPT_NO,DEPT_NAME,BOSS_NO,MGR_DEPT_NO) values (13,'Commerce파트','it1013',NULL);
Insert into MBMS.DEPARTMENT (DEPT_NO,DEPT_NAME,BOSS_NO,MGR_DEPT_NO) values (14,'CRM파트','it1014',NULL);
Insert into MBMS.DEPARTMENT (DEPT_NO,DEPT_NAME,BOSS_NO,MGR_DEPT_NO) values (15,'데이터사업파트','it1015',NULL);
Insert into MBMS.DEPARTMENT (DEPT_NO,DEPT_NAME,BOSS_NO,MGR_DEPT_NO) values (16,'유통/물류파트','it1016',NULL);
Insert into MBMS.DEPARTMENT (DEPT_NO,DEPT_NAME,BOSS_NO,MGR_DEPT_NO) values (0,'GSITM','CEO',NULL);

UPDATE MBMS.DEPARTMENT SET MGR_DEPT_NO = 0 WHERE DEPT_NO = 10;
UPDATE MBMS.DEPARTMENT SET MGR_DEPT_NO = 10 WHERE DEPT_NO = 11;
UPDATE MBMS.DEPARTMENT SET MGR_DEPT_NO = 10 WHERE DEPT_NO = 12;
UPDATE MBMS.DEPARTMENT SET MGR_DEPT_NO = 12 WHERE DEPT_NO = 13;
UPDATE MBMS.DEPARTMENT SET MGR_DEPT_NO = 12 WHERE DEPT_NO = 14;
UPDATE MBMS.DEPARTMENT SET MGR_DEPT_NO = 12 WHERE DEPT_NO = 15;
UPDATE MBMS.DEPARTMENT SET MGR_DEPT_NO = 12 WHERE DEPT_NO = 16;
UPDATE MBMS.DEPARTMENT SET MGR_DEPT_NO = 0 WHERE DEPT_NO = 0;


ALTER SEQUENCE Department_SEQ INCREMENT BY 17;
select Department_SEQ.nextval from dual;
alter sequence Department_SEQ increment by 1;
